version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.4
jobs:
  build:
    working_directory: ~/nodejs-express-mongodb
    docker:
      - image: circleci/node:12.0.0
      - image: mongo:4.2.1
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: test
          command: npm test
      - run: # run code coverage report
          name: code-coverage
          command: npm run coverage